insert into USER (user_id, user_name, email) values (1, 'Mehmet Emre Gürsoy', 'EMREGURSOY@ku.edu.tr');
insert into USER (user_id, user_name, email) values (2, 'Ecenaz Eğri', 'eegri21@ku.edu.tr');
insert into USER (user_id, user_name, email) values (3, 'Simge Akgül', 'simgeakgul20@ku.edu.tr');
insert into USER (user_id, user_name, email) values (4, 'Ahmet Kutluğ Alperen Kars', 'akars20@ku.edu.tr');
insert into USER (user_id, user_name, email) values (5, 'Jaclin Causnett', 'jcausnett4@spotify.com');
insert into USER (user_id, user_name, email) values (6, 'Ly Niland', 'lniland5@accuweather.com');
insert into USER (user_id, user_name, email) values (7, 'Shep Brea', 'sbrea6@marriott.com');
insert into USER (user_id, user_name, email) values (8, 'Kenon Mechem', 'kmechem7@ucoz.ru');
insert into USER (user_id, user_name, email) values (9, 'Malvin Chat', 'mchat8@slashdot.org');
insert into USER (user_id, user_name, email) values (10, 'Helena Cran', 'hcran9@usgs.gov');
insert into USER (user_id, user_name, email) values (11, 'Jeth Franzotto', 'jfranzottoa@auda.org.au');
insert into USER (user_id, user_name, email) values (12, 'Lexine Desesquelle', 'ldesesquelleb@bbc.co.uk');
insert into USER (user_id, user_name, email) values (13, 'Emelyne Loraine', 'elorainec@cmu.edu');
insert into USER (user_id, user_name, email) values (14, 'Annnora Coughtrey', 'acoughtreyd@imdb.com');
insert into USER (user_id, user_name, email) values (15, 'Leonie Dorre', 'ldorree@linkedin.com');
insert into USER (user_id, user_name, email) values (16, 'Mandi Ray', 'mrayf@go.com');
insert into USER (user_id, user_name, email) values (17, 'Yurik Pane', 'ypaneg@nasa.gov');
insert into USER (user_id, user_name, email) values (18, 'Kaela Frewer', 'kfrewerh@loc.gov');
insert into USER (user_id, user_name, email) values (19, 'Darnall Verheyden', 'dverheydeni@wikispaces.com');
insert into USER (user_id, user_name, email) values (20, 'Glori Brodway', 'gbrodwayj@feedburner.com');
